spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
  h2: 
    console:
      enable: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
        hibernate:
         dialect: org.hibernate.dialect.H2Dialect
  jackson:
    serialization:
      fail-on-empty-beans: false





